version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    target-branch: "work-for-release-0.23.x"
    ignore:
    - dependency-name: ch.qos.logback:*
      versions:
        - ">= 1.3.0"
    # https://github.com/killbill/killbill-oss-parent/issues/40
    - dependency-name: io.jooby:*
    - dependency-name: io.netty:*
      versions:
        - ">= 5.0.0"
    - dependency-name: jakarta.activation:jakarta.activation-api
      versions:
        - ">= 2.0.0"
    - dependency-name: jakarta.ws.rs:jakarta.ws.rs-api
      versions:
        - ">= 3.0.0"
    - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
      versions:
        - ">= 3.0.0"
    - dependency-name: org.antlr:stringtemplate
      versions:
        - ">= 4.0.0"
    # https://github.com/killbill/killbill-oss-parent/issues/36
    - dependency-name: org.apache.shiro:*
      versions:
        - "< 2.0.0"
    - dependency-name: org.eclipse.jetty:*
      versions:
        - ">= 11.0.0"
    # https://github.com/killbill/killbill-oss-parent/pull/431#issuecomment-1112488332
    - dependency-name: org.ehcache:*
      versions:
        - ">= 3.10.0"
    # We've forked the code
    - dependency-name: org.flywaydb:*
    - dependency-name: org.glassfish.hk2:*
      versions:
        - ">= 3.0.0"
    - dependency-name: org.glassfish.jaxb:jaxb-runtime
      versions:
        - ">= 3.0.0"
    # https://eclipse-ee4j.github.io/jersey.github.io/documentation/3.0.0/user-guide.html#mig-2.26
    - dependency-name: org.glassfish.jersey.*:*
      versions:
        - ">= 3.0.0"
    # https://github.com/killbill/killbill-oss-parent/issues/40
    - dependency-name: org.jooby:*
      versions:
        - ">= 2.0.0"
    # https://github.com/killbill/killbill-oss-parent/pull/411#issuecomment-1111986725
    - dependency-name: org.jooq:*
      versions:
        - ">= 3.16.0"
    # derby 10.16.x require Java 17
    - dependency-name: org.apache.derby:*
      versions:
        - ">= 10.16.0.0"
    # Some problems:
    #   - annotation-api 2.x start using jakarta.* instead of javax.*
    #   - attempt to update jersey version to 3.x.x (to match jakarta.annotation 2.x.x version) will fail because
    #     HttpServlet not in javax.http anymore
    - dependency-name: jakarta.annotation:*
      versions:
        - ">= 2.0.0"
    # Start from 1.4.0, LogService implements LoggerFactory. See:
    # - 1.3.0 : https://docs.osgi.org/javadoc/r6/enterprise/org/osgi/service/log/LogService.html
    # - 1.4.0 : https://docs.osgi.org/javadoc/osgi.cmpn/7.0.0/org/osgi/service/log/LogService.html
    - dependency-name: org.osgi:org.osgi.service.log
      versions:
        - ">= 1.4.0"
