version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "work-for-release-0.23.x"
    ignore:
    - dependency-name: ch.qos.logback:*
      versions:
        - ">= 1.3.0"
    # https://github.com/killbill/killbill-oss-parent/issues/40
    - dependency-name: io.jooby:*
    - dependency-name: io.netty:*
      versions:
        - ">= 5.0.0"
    - dependency-name: jakarta.activation:jakarta.activation-api
      versions:
        - ">= 2.0.0"
    - dependency-name: jakarta.ws.rs:jakarta.ws.rs-api
      versions:
        - ">= 3.0.0"
    - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
      versions:
        - ">= 3.0.0"
    - dependency-name: org.antlr:stringtemplate
      versions:
        - ">= 4.0.0"
    # https://github.com/killbill/killbill-oss-parent/issues/36
    - dependency-name: org.apache.shiro:*
      versions:
        - "< 2.0.0"
    - dependency-name: org.eclipse.jetty:*
      versions:
        - ">= 10.0.0"
    # We've forked the code
    - dependency-name: org.flywaydb:*
    - dependency-name: org.glassfish.hk2:*
      versions:
        - ">= 3.0.0"
    - dependency-name: org.glassfish.jaxb:jaxb-runtime
      versions:
        - ">= 3.0.0"
    - dependency-name: org.glassfish.jersey.*:*
      versions:
        - ">= 3.0.0"
    # https://github.com/killbill/killbill-oss-parent/issues/40
    - dependency-name: org.jooby:*
      versions:
        - ">= 2.0.0"
    - dependency-name: org.jruby:*
      versions:
        - ">= 1.8.0"
    - dependency-name: org.ow2.asm:asm
      versions:
        - ">= 6.0.0"
    - dependency-name: org.slf4j:*
      versions:
        - ">= 2.0.0"
