name: ci

on:
  - pull_request
  - push
  - workflow_dispatch

env:
  MAVEN_FLAGS: "-B -ff -Dcheck.skip-spotbugs=true -DskipTests=true"
  MAVEN_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 16
          - 17
        java-distribution:
          - adopt
        suite:
          - mysql
    steps:
      - name: Checkout killbill-oss-parent
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-oss-parent
          path: killbill-oss-parent
      - name: Checkout killbill-commons
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-commons
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-commons
      - name: Checkout killbill-plugin-framework-java
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-plugin-framework-java
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-plugin-framework-java
      - name: Checkout killbill-platform
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-platform
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-platform
      - name: Checkout killbill-client-java
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-client-java
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-client-java
      - name: Checkout killbill
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill
          ref: refs/heads/work-for-release-0.23.x
          path: killbill
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Download dependencies and setup the various pom.xml
        run: |
          pushd $GITHUB_WORKSPACE/killbill-oss-parent
          pomVersion=$(mvn ${MAVEN_FLAGS} help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn -version
          mvn ${MAVEN_FLAGS} clean install
          popd

          declare -A property=(
            [killbill-commons]=killbill-commons.version
            [killbill-plugin-framework-java]=killbill-base-plugin.version
            [killbill-platform]=killbill-platform.version
            [killbill-client-java]=killbill-client.version
          )
          for i in killbill-commons killbill-plugin-framework-java killbill-platform killbill-client-java; do
            pushd $GITHUB_WORKSPACE/$i
            echo "Resolving current $i version"
            version=$(mvn ${MAVEN_FLAGS} help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "Current $i version is $version"
            echo "Updating $i parent pom.xml to $pomVersion"
            mvn ${MAVEN_FLAGS} versions:update-parent -DallowSnapshots -DgenerateBackupPoms=false -DparentVersion="[$pomVersion]"
            echo "$i pom.xml changes:"
            git --no-pager diff
            echo "Building $i"
            mvn ${MAVEN_FLAGS} clean install
            popd

            pushd $GITHUB_WORKSPACE/killbill-oss-parent
            echo "Updating ${property[$i]} in parent pom.xml to $version"
            mvn ${MAVEN_FLAGS} versions:set-property -Dproperty=${property[$i]} -DnewVersion=$version
            echo "killbill-oss-parent pom.xml changes:"
            git --no-pager diff
            echo "Building killbill-oss-parent"
            mvn ${MAVEN_FLAGS} clean install
            popd
          done

