name: ci

on:
  - pull_request
  - push
  - workflow_dispatch

env:
  MAVEN_FLAGS: "-B -ff -Dcheck.skip-spotbugs=true -DskipTests=true"
  MAVEN_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 16
        java-distribution:
          - adopt
        suite:
          - mysql
    steps:
      - name: Checkout killbill-oss-parent
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-oss-parent
          path: killbill-oss-parent
      - name: Checkout killbill-commons
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-commons
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-commons
      - name: Checkout killbill-plugin-framework-java
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-plugin-framework-java
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-plugin-framework-java
      - name: Checkout killbill-platform
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-platform
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-platform
      - name: Checkout killbill-client-java
        uses: actions/checkout@v2
        with:
          repository: killbill/killbill-client-java
          ref: refs/heads/work-for-release-0.23.x
          path: killbill-client-java
      - name: Checkout killbill
        uses: actions/checkout@v2
        with:
          repository: vnandwana/killbill
          ref: refs/heads/work-for-release-0.23.x
          path: killbill
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Run killbill tests
        run: |
          i=killbill
          pushd $GITHUB_WORKSPACE/$i
          echo "$i pom.xml changes:"
          git --no-pager diff
          echo "Running $i ${{ matrix.suite }} tests"
          # Flaky...
          $GITHUB_WORKSPACE/killbill-oss-parent/bin/retry mvn clean install -P${{ matrix.suite }} -pl jaxrs -Dkillbill.test.apiListenerDelay=120000
          popd
